Option Strict Off
Option Explicit On
Module SRAET53_IEV
	Public Const SSS_MAX_DB As Short = 20
	Public DB_PARA(SSS_MAX_DB) As TYPE_DB_PARA
	Public Const SSS_PrgId As String = "UODET53"
	Public Const SSS_PrgNm As String = "ì¸ã‡è¡çû"
	Public Const SSS_FraId As String = "ET1"
	
	Sub Init_Fil() 'Generated.
		'    '
		'    DBN_JDNTRA = 0
		'    DB_PARA(DBN_JDNTRA).tblid = "JDNTRA"
		'    DB_PARA(DBN_JDNTRA).DBID = "USR1"
		'    SSS_MFIL = DBN_JDNTRA
		'    '
		'    DBN_JDNTHA = 1
		'    DB_PARA(DBN_JDNTHA).tblid = "JDNTHA"
		'    DB_PARA(DBN_JDNTHA).DBID = "USR1"
		'    '
		'    DBN_TOKMTA = 2
		'    DB_PARA(DBN_TOKMTA).tblid = "TOKMTA"
		'    DB_PARA(DBN_TOKMTA).DBID = "USR1"
		'    '
		'    DBN_TANMTA = 3
		'    DB_PARA(DBN_TANMTA).tblid = "TANMTA"
		'    DB_PARA(DBN_TANMTA).DBID = "USR1"
		'    '
		'    DBN_NHSMTA = 4
		'    DB_PARA(DBN_NHSMTA).tblid = "NHSMTA"
		'    DB_PARA(DBN_NHSMTA).DBID = "USR1"
		'    '
		'    DBN_SOUMTA = 5
		'    DB_PARA(DBN_SOUMTA).tblid = "SOUMTA"
		'    DB_PARA(DBN_SOUMTA).DBID = "USR1"
		'    '
		'    DBN_HINMTA = 6
		'    DB_PARA(DBN_HINMTA).tblid = "HINMTA"
		'    DB_PARA(DBN_HINMTA).DBID = "USR1"
		'    '
		'    DBN_SYSTBA = 7
		'    DB_PARA(DBN_SYSTBA).tblid = "SYSTBA"
		'    DB_PARA(DBN_SYSTBA).DBID = "USR1"
		'    '
		'    DBN_SYSTBB = 8
		'    DB_PARA(DBN_SYSTBB).tblid = "SYSTBB"
		'    DB_PARA(DBN_SYSTBB).DBID = "USR1"
		'    '
		'    DBN_SYSTBC = 9
		'    DB_PARA(DBN_SYSTBC).tblid = "SYSTBC"
		'    DB_PARA(DBN_SYSTBC).DBID = "USR1"
		'    '
		'    DBN_SYSTBD = 10
		'    DB_PARA(DBN_SYSTBD).tblid = "SYSTBD"
		'    DB_PARA(DBN_SYSTBD).DBID = "USR1"
		'    '
		'    DBN_SYSTBF = 11
		'    DB_PARA(DBN_SYSTBF).tblid = "SYSTBF"
		'    DB_PARA(DBN_SYSTBF).DBID = "USR1"
		'    '
		'    DBN_SYSTBG = 12
		'    DB_PARA(DBN_SYSTBG).tblid = "SYSTBG"
		'    DB_PARA(DBN_SYSTBG).DBID = "USR1"
		'    '
		'    DBN_SYSTBH = 13
		'    DB_PARA(DBN_SYSTBH).tblid = "SYSTBH"
		'    DB_PARA(DBN_SYSTBH).DBID = "USR1"
		'    '
		'    DBN_CLSMTA = 14
		'    DB_PARA(DBN_CLSMTA).tblid = "CLSMTA"
		'    DB_PARA(DBN_CLSMTA).DBID = "USR1"
		'    '
		'    DBN_CLSMTB = 15
		'    DB_PARA(DBN_CLSMTB).tblid = "CLSMTB"
		'    DB_PARA(DBN_CLSMTB).DBID = "USR1"
		'    '
		'    DBN_HINMTB = 16
		'    DB_PARA(DBN_HINMTB).tblid = "HINMTB"
		'    DB_PARA(DBN_HINMTB).DBID = "USR1"
		'    '
		'    DBN_TOKMTB = 17
		'    DB_PARA(DBN_TOKMTB).tblid = "TOKMTB"
		'    DB_PARA(DBN_TOKMTB).DBID = "USR1"
		'    '
		'    DBN_UODET01 = 18
		'    DB_PARA(DBN_UODET01).tblid = "UODET01"
		'    DB_PARA(DBN_UODET01).DBID = "USR2"
		'    '
		'    DBN_SYSTBI = 19
		'    DB_PARA(DBN_SYSTBI).tblid = "SYSTBI"
		'    DB_PARA(DBN_SYSTBI).DBID = "USR1"
		'    '
		'    DBN_HINSMA = -1
		'    '
		'    DBN_TANSMA = -2
		'    '
		'    DBN_TOKSMB = -3
		'    '
		'    DBN_TOKSMC = -4
		'
		'    SSS_BILFL = 1
		'    SSS_LSTMFIL = DBN_UODET01
	End Sub
	
	Sub SCR_FromHINMTA(ByVal De As Short) 'Generated.
		'    Call DP_SSSMAIN_GNKTK(De, DB_HINMTA.GNKTK)
		'    Call DP_SSSMAIN_HINCD(De, DB_HINMTA.HINCD)
		'    Call DP_SSSMAIN_HINKB(De, DB_HINMTA.HINKB)
		'    Call DP_SSSMAIN_HINMSTKB(De, DB_HINMTA.HINMSTKB)
		'    Call DP_SSSMAIN_HINNMA(De, DB_HINMTA.HINNMA)
		'    Call DP_SSSMAIN_HINNMB(De, DB_HINMTA.HINNMB)
		'    Call DP_SSSMAIN_HINNMMKB(De, DB_HINMTA.HINNMMKB)
		'    Call DP_SSSMAIN_HINZEIKB(De, DB_HINMTA.HINZEIKB)
		'    Call DP_SSSMAIN_HRTDD(De, DB_HINMTA.HRTDD)
		'    'Call DP_SSSMAIN_IRISU(De, DB_HINMTA.IRISU)
		'    Call DP_SSSMAIN_MAKCD(De, DB_HINMTA.MAKCD)
		'    'Call DP_SSSMAIN_MRPKB(De, DB_HINMTA.MRPKB)
		'    Call DP_SSSMAIN_ORTDD(De, DB_HINMTA.ORTDD)
		'    'Call DP_SSSMAIN_TNKDT(De, DB_HINMTA.TNKDT)
		'    Call DP_SSSMAIN_UNTCD(De, DB_HINMTA.UNTCD)
		'    Call DP_SSSMAIN_UNTNM(De, DB_HINMTA.UNTNM)
		'    Call DP_SSSMAIN_ZAIKB(De, DB_HINMTA.ZAIKB)
		'    Call DP_SSSMAIN_ZEIRNKKB(De, DB_HINMTA.ZEIRNKKB)
	End Sub
	
	Sub HINMTA_FromSCR(ByVal De As Short) 'Generated.
		'    DB_HINMTA.GNKTK = RD_SSSMAIN_GNKTK(De)
		'    DB_HINMTA.HINCD = RD_SSSMAIN_HINCD(De)
		'    DB_HINMTA.HINKB = RD_SSSMAIN_HINKB(De)
		'    DB_HINMTA.HINMSTKB = RD_SSSMAIN_HINMSTKB(De)
		'    DB_HINMTA.HINNMA = RD_SSSMAIN_HINNMA(De)
		'    DB_HINMTA.HINNMB = RD_SSSMAIN_HINNMB(De)
		'    DB_HINMTA.HINNMMKB = RD_SSSMAIN_HINNMMKB(De)
		'    DB_HINMTA.HINZEIKB = RD_SSSMAIN_HINZEIKB(De)
		'    DB_HINMTA.HRTDD = RD_SSSMAIN_HRTDD(De)
		'    DB_HINMTA.IRISU = RD_SSSMAIN_IRISU(De)
		'    DB_HINMTA.MAKCD = RD_SSSMAIN_MAKCD(De)
		'    DB_HINMTA.MRPKB = RD_SSSMAIN_MRPKB(De)
		'    DB_HINMTA.ORTDD = RD_SSSMAIN_ORTDD(De)
		'    DB_HINMTA.TNKDT = RD_SSSMAIN_TNKDT(De)
		'    DB_HINMTA.UNTCD = RD_SSSMAIN_UNTCD(De)
		'    DB_HINMTA.UNTNM = RD_SSSMAIN_UNTNM(De)
		'    DB_HINMTA.ZAIKB = RD_SSSMAIN_ZAIKB(De)
		'    DB_HINMTA.ZEIRNKKB = RD_SSSMAIN_ZEIRNKKB(De)
		'    DB_HINMTA.OPEID = SSS_OPEID
		'    DB_HINMTA.CLTID = SSS_CLTID
		'    If Trim$(DB_ORATM) = "" Or Trim$(DB_ORADT) = "" Then
		'        DB_HINMTA.WRTTM = Format(Now, "hhmmss")
		'        DB_HINMTA.WRTDT = Format(Now, "YYYYMMDD")
		'    Else
		'        DB_HINMTA.WRTTM = DB_ORATM
		'        DB_HINMTA.WRTDT = DB_ORADT
		'    End If
	End Sub
	
	Sub SCR_FromJDNTHA(ByVal De As Short) 'Generated.
		'    Call DP_SSSMAIN_CLTID(De, DB_JDNTHA.CLTID)
		'    Call DP_SSSMAIN_DATKB(De, DB_JDNTHA.DATKB)
		'    Call DP_SSSMAIN_DEFNOKDT(De, DB_JDNTHA.DEFNOKDT)
		'    Call DP_SSSMAIN_DENCM(De, DB_JDNTHA.DENCM)
		'    Call DP_SSSMAIN_JDNDT(De, DB_JDNTHA.JDNDT)
		'    Call DP_SSSMAIN_JDNENDKB(De, DB_JDNTHA.JDNENDKB)
		'    Call DP_SSSMAIN_JDNNO(De, DB_JDNTHA.JDNNO)
		'    Call DP_SSSMAIN_LSTID(De, DB_JDNTHA.LSTID)
		'    Call DP_SSSMAIN_NHSCD(De, DB_JDNTHA.NHSCD)
		'    Call DP_SSSMAIN_NHSMSTKB(De, DB_JDNTHA.NHSMSTKB)
		'    Call DP_SSSMAIN_NHSNMMKB(De, DB_JDNTHA.NHSNMMKB)
		'    Call DP_SSSMAIN_NHSRN(De, DB_JDNTHA.NHSRN)
		'    Call DP_SSSMAIN_OPEID(De, DB_JDNTHA.OPEID)
		'    Call DP_SSSMAIN_SBAUODKN(De, DB_JDNTHA.SBAUODKN)
		'    Call DP_SSSMAIN_SOUCD(De, DB_JDNTHA.SOUCD)
		'    Call DP_SSSMAIN_SOUNM(De, DB_JDNTHA.SOUNM)
		'    Call DP_SSSMAIN_TANCD(De, DB_JDNTHA.TANCD)
		'    Call DP_SSSMAIN_TANMSTKB(De, DB_JDNTHA.TANMSTKB)
		'    Call DP_SSSMAIN_TANNM(De, DB_JDNTHA.TANNM)
		'    Call DP_SSSMAIN_TOKCD(De, DB_JDNTHA.TOKCD)
		'    Call DP_SSSMAIN_TOKKDWKB(De, DB_JDNTHA.TOKKDWKB)
		'    Call DP_SSSMAIN_TOKKESCC(De, DB_JDNTHA.TOKKESCC)
		'    Call DP_SSSMAIN_TOKKESDD(De, DB_JDNTHA.TOKKESDD)
		'    Call DP_SSSMAIN_TOKMSTKB(De, DB_JDNTHA.TOKMSTKB)
		'    Call DP_SSSMAIN_TOKNMMKB(De, DB_JDNTHA.TOKNMMKB)
		'    Call DP_SSSMAIN_TOKRN(De, DB_JDNTHA.TOKRN)
		'    Call DP_SSSMAIN_TOKRPSKB(De, DB_JDNTHA.TOKRPSKB)
		'    Call DP_SSSMAIN_TOKSDWKB(De, DB_JDNTHA.TOKSDWKB)
		'    Call DP_SSSMAIN_TOKSEICD(De, DB_JDNTHA.TOKSEICD)
		'    Call DP_SSSMAIN_TOKSMECC(De, DB_JDNTHA.TOKSMECC)
		'    Call DP_SSSMAIN_TOKSMEDD(De, DB_JDNTHA.TOKSMEDD)
		'    Call DP_SSSMAIN_TOKSMEKB(De, DB_JDNTHA.TOKSMEKB)
		'    Call DP_SSSMAIN_TOKZCLKB(De, DB_JDNTHA.TOKZCLKB)
		'    Call DP_SSSMAIN_TOKZEIKB(De, DB_JDNTHA.TOKZEIKB)
		'    Call DP_SSSMAIN_TOKZRNKB(De, DB_JDNTHA.TOKZRNKB)
		'    Call DP_SSSMAIN_ZKTKB(De, DB_JDNTHA.ZKTKB)
		'    Call DP_SSSMAIN_ZKTNM(De, DB_JDNTHA.ZKTNM)
	End Sub
	
	Sub JDNTHA_FromSCR(ByVal De As Short) 'Generated.
		'    DB_JDNTHA.CLTID = RD_SSSMAIN_CLTID(De)
		'    DB_JDNTHA.DATKB = RD_SSSMAIN_DATKB(De)
		'    DB_JDNTHA.DEFNOKDT = RD_SSSMAIN_DEFNOKDT(De)
		'    DB_JDNTHA.DENCM = RD_SSSMAIN_DENCM(De)
		'    DB_JDNTHA.JDNDT = RD_SSSMAIN_JDNDT(De)
		'    DB_JDNTHA.JDNENDKB = RD_SSSMAIN_JDNENDKB(De)
		'    DB_JDNTHA.JDNNO = RD_SSSMAIN_JDNNO(De)
		'    DB_JDNTHA.LSTID = RD_SSSMAIN_LSTID(De)
		'    DB_JDNTHA.NHSCD = RD_SSSMAIN_NHSCD(De)
		'    DB_JDNTHA.NHSMSTKB = RD_SSSMAIN_NHSMSTKB(De)
		'    DB_JDNTHA.NHSNMMKB = RD_SSSMAIN_NHSNMMKB(De)
		'    DB_JDNTHA.NHSRN = RD_SSSMAIN_NHSRN(De)
		'    DB_JDNTHA.OPEID = RD_SSSMAIN_OPEID(De)
		'    DB_JDNTHA.SBAUODKN = RD_SSSMAIN_SBAUODKN(De)
		'    DB_JDNTHA.SOUCD = RD_SSSMAIN_SOUCD(De)
		'    DB_JDNTHA.SOUNM = RD_SSSMAIN_SOUNM(De)
		'    DB_JDNTHA.TANCD = RD_SSSMAIN_TANCD(De)
		'    DB_JDNTHA.TANMSTKB = RD_SSSMAIN_TANMSTKB(De)
		'    DB_JDNTHA.TANNM = RD_SSSMAIN_TANNM(De)
		'    DB_JDNTHA.TOKCD = RD_SSSMAIN_TOKCD(De)
		'    DB_JDNTHA.TOKKDWKB = RD_SSSMAIN_TOKKDWKB(De)
		'    DB_JDNTHA.TOKKESCC = RD_SSSMAIN_TOKKESCC(De)
		'    DB_JDNTHA.TOKKESDD = RD_SSSMAIN_TOKKESDD(De)
		'    DB_JDNTHA.TOKMSTKB = RD_SSSMAIN_TOKMSTKB(De)
		'    DB_JDNTHA.TOKNMMKB = RD_SSSMAIN_TOKNMMKB(De)
		'    DB_JDNTHA.TOKRN = RD_SSSMAIN_TOKRN(De)
		'    DB_JDNTHA.TOKRPSKB = RD_SSSMAIN_TOKRPSKB(De)
		'    DB_JDNTHA.TOKSDWKB = RD_SSSMAIN_TOKSDWKB(De)
		'    DB_JDNTHA.TOKSEICD = RD_SSSMAIN_TOKSEICD(De)
		'    DB_JDNTHA.TOKSMECC = RD_SSSMAIN_TOKSMECC(De)
		'    DB_JDNTHA.TOKSMEDD = RD_SSSMAIN_TOKSMEDD(De)
		'    DB_JDNTHA.TOKSMEKB = RD_SSSMAIN_TOKSMEKB(De)
		'    DB_JDNTHA.TOKZCLKB = RD_SSSMAIN_TOKZCLKB(De)
		'    DB_JDNTHA.TOKZEIKB = RD_SSSMAIN_TOKZEIKB(De)
		'    DB_JDNTHA.TOKZRNKB = RD_SSSMAIN_TOKZRNKB(De)
		'    DB_JDNTHA.ZKTKB = RD_SSSMAIN_ZKTKB(De)
		'    DB_JDNTHA.ZKTNM = RD_SSSMAIN_ZKTNM(De)
		'    DB_JDNTHA.OPEID = SSS_OPEID
		'    DB_JDNTHA.CLTID = SSS_CLTID
		'    If Trim$(DB_ORATM) = "" Or Trim$(DB_ORADT) = "" Then
		'        DB_JDNTHA.WRTTM = Format(Now, "hhmmss")
		'        DB_JDNTHA.WRTDT = Format(Now, "YYYYMMDD")
		'    Else
		'        DB_JDNTHA.WRTTM = DB_ORATM
		'        DB_JDNTHA.WRTDT = DB_ORADT
		'    End If
	End Sub
	
	Sub SCR_FromMfil(ByVal De As Short) 'Generated.
		'    Call DP_SSSMAIN_CASSU(De, DB_JDNTRA.CASSU)
		'    Call DP_SSSMAIN_CLTID(De, DB_JDNTRA.CLTID)
		'    Call DP_SSSMAIN_DATKB(De, DB_JDNTRA.DATKB)
		'    Call DP_SSSMAIN_DEFNOKDT(De, DB_JDNTRA.NOKDT)
		'    Call DP_SSSMAIN_GNKKN(De, DB_JDNTRA.GNKKN)
		'    Call DP_SSSMAIN_GNKTK(De, DB_JDNTRA.GNKTK)
		'    Call DP_SSSMAIN_HINCD(De, DB_JDNTRA.HINCD)
		'    Call DP_SSSMAIN_HINKB(De, DB_JDNTRA.HINKB)
		'    Call DP_SSSMAIN_HINMSTKB(De, DB_JDNTRA.HINMSTKB)
		'    Call DP_SSSMAIN_HINNMA(De, DB_JDNTRA.HINNMA)
		'    Call DP_SSSMAIN_HINNMB(De, DB_JDNTRA.HINNMB)
		'    Call DP_SSSMAIN_HINNMMKB(De, DB_JDNTRA.HINNMMKB)
		'    Call DP_SSSMAIN_HINZEIKB(De, DB_JDNTRA.HINZEIKB)
		'    Call DP_SSSMAIN_HRTDD(De, DB_JDNTRA.HRTDD)
		'    Call DP_SSSMAIN_IRISU(De, DB_JDNTRA.IRISU)
		'    Call DP_SSSMAIN_JDNDT(De, DB_JDNTRA.JDNDT)
		'    Call DP_SSSMAIN_JDNNO(De, DB_JDNTRA.JDNNO)
		'    Call DP_SSSMAIN_LINCMA(De, DB_JDNTRA.LINCMA)
		'    Call DP_SSSMAIN_LINCMB(De, DB_JDNTRA.LINCMB)
		'    Call DP_SSSMAIN_LINNO(De, DB_JDNTRA.LINNO)
		'    Call DP_SSSMAIN_LSTID(De, DB_JDNTRA.LSTID)
		'    Call DP_SSSMAIN_MAKCD(De, DB_JDNTRA.MAKCD)
		'    Call DP_SSSMAIN_MRPKB(De, DB_JDNTRA.MRPKB)
		'    Call DP_SSSMAIN_NHSCD(De, DB_JDNTRA.NHSCD)
		'    Call DP_SSSMAIN_NHSMSTKB(De, DB_JDNTRA.NHSMSTKB)
		'    Call DP_SSSMAIN_OPEID(De, DB_JDNTRA.OPEID)
		'    Call DP_SSSMAIN_ORTDD(De, DB_JDNTRA.ORTDD)
		'    Call DP_SSSMAIN_RECNO(De, DB_JDNTRA.RECNO)
		'    Call DP_SSSMAIN_SOUCD(De, DB_JDNTRA.SOUCD)
		'    Call DP_SSSMAIN_TANCD(De, DB_JDNTRA.TANCD)
		'    Call DP_SSSMAIN_TANMSTKB(De, DB_JDNTRA.TANMSTKB)
		'    Call DP_SSSMAIN_TOKCD(De, DB_JDNTRA.TOKCD)
		'    Call DP_SSSMAIN_TOKMSTKB(De, DB_JDNTRA.TOKMSTKB)
		'    Call DP_SSSMAIN_TOKSEICD(De, DB_JDNTRA.TOKSEICD)
		'    Call DP_SSSMAIN_UNTCD(De, DB_JDNTRA.UNTCD)
		'    Call DP_SSSMAIN_UNTNM(De, DB_JDNTRA.UNTNM)
		'    Call DP_SSSMAIN_UODKN(De, DB_JDNTRA.UODKN)
		'    Call DP_SSSMAIN_UODSU(De, DB_JDNTRA.UODSU)
		'    Call DP_SSSMAIN_UODTK(De, DB_JDNTRA.UODTK)
		'    Call DP_SSSMAIN_ZAIKB(De, DB_JDNTRA.ZAIKB)
		'    Call DP_SSSMAIN_ZEIRNKKB(De, DB_JDNTRA.ZEIRNKKB)
		'    Call DP_SSSMAIN_ZKTKB(De, DB_JDNTRA.ZKTKB)
	End Sub
	
	Sub Mfil_FromSCR(ByVal De As Short) 'Generated.
		'    DB_JDNTRA.CASSU = RD_SSSMAIN_CASSU(De)
		'    DB_JDNTRA.CLTID = RD_SSSMAIN_CLTID(De)
		'    DB_JDNTRA.DATKB = RD_SSSMAIN_DATKB(De)
		'    DB_JDNTRA.NOKDT = RD_SSSMAIN_DEFNOKDT(De)
		'    DB_JDNTRA.GNKKN = RD_SSSMAIN_GNKKN(De)
		'    DB_JDNTRA.GNKTK = RD_SSSMAIN_GNKTK(De)
		'    DB_JDNTRA.HINCD = RD_SSSMAIN_HINCD(De)
		'    DB_JDNTRA.HINKB = RD_SSSMAIN_HINKB(De)
		'    DB_JDNTRA.HINMSTKB = RD_SSSMAIN_HINMSTKB(De)
		'    DB_JDNTRA.HINNMA = RD_SSSMAIN_HINNMA(De)
		'    DB_JDNTRA.HINNMB = RD_SSSMAIN_HINNMB(De)
		'    DB_JDNTRA.HINNMMKB = RD_SSSMAIN_HINNMMKB(De)
		'    DB_JDNTRA.HINZEIKB = RD_SSSMAIN_HINZEIKB(De)
		'    DB_JDNTRA.HRTDD = RD_SSSMAIN_HRTDD(De)
		'    DB_JDNTRA.IRISU = RD_SSSMAIN_IRISU(De)
		'    DB_JDNTRA.JDNDT = RD_SSSMAIN_JDNDT(De)
		'    DB_JDNTRA.JDNNO = RD_SSSMAIN_JDNNO(De)
		'    DB_JDNTRA.LINCMA = RD_SSSMAIN_LINCMA(De)
		'    DB_JDNTRA.LINCMB = RD_SSSMAIN_LINCMB(De)
		'    DB_JDNTRA.LINNO = RD_SSSMAIN_LINNO(De)
		'    DB_JDNTRA.LSTID = RD_SSSMAIN_LSTID(De)
		'    DB_JDNTRA.MAKCD = RD_SSSMAIN_MAKCD(De)
		'    DB_JDNTRA.MRPKB = RD_SSSMAIN_MRPKB(De)
		'    DB_JDNTRA.NHSCD = RD_SSSMAIN_NHSCD(De)
		'    DB_JDNTRA.NHSMSTKB = RD_SSSMAIN_NHSMSTKB(De)
		'    DB_JDNTRA.OPEID = RD_SSSMAIN_OPEID(De)
		'    DB_JDNTRA.ORTDD = RD_SSSMAIN_ORTDD(De)
		'    DB_JDNTRA.RECNO = RD_SSSMAIN_RECNO(De)
		'    DB_JDNTRA.SOUCD = RD_SSSMAIN_SOUCD(De)
		'    DB_JDNTRA.TANCD = RD_SSSMAIN_TANCD(De)
		'    DB_JDNTRA.TANMSTKB = RD_SSSMAIN_TANMSTKB(De)
		'    DB_JDNTRA.TOKCD = RD_SSSMAIN_TOKCD(De)
		'    DB_JDNTRA.TOKMSTKB = RD_SSSMAIN_TOKMSTKB(De)
		'    DB_JDNTRA.TOKSEICD = RD_SSSMAIN_TOKSEICD(De)
		'    DB_JDNTRA.UNTCD = RD_SSSMAIN_UNTCD(De)
		'    DB_JDNTRA.UNTNM = RD_SSSMAIN_UNTNM(De)
		'    DB_JDNTRA.UODKN = RD_SSSMAIN_UODKN(De)
		'    DB_JDNTRA.UODSU = RD_SSSMAIN_UODSU(De)
		'    DB_JDNTRA.UODTK = RD_SSSMAIN_UODTK(De)
		'    DB_JDNTRA.ZAIKB = RD_SSSMAIN_ZAIKB(De)
		'    DB_JDNTRA.ZEIRNKKB = RD_SSSMAIN_ZEIRNKKB(De)
		'    DB_JDNTRA.ZKTKB = RD_SSSMAIN_ZKTKB(De)
		'    DB_JDNTRA.OPEID = SSS_OPEID
		'    DB_JDNTRA.CLTID = SSS_CLTID
		'    If Trim$(DB_ORATM) = "" Or Trim$(DB_ORADT) = "" Then
		'        DB_JDNTRA.WRTTM = Format(Now, "hhmmss")
		'        DB_JDNTRA.WRTDT = Format(Now, "YYYYMMDD")
		'    Else
		'        DB_JDNTRA.WRTTM = DB_ORATM
		'        DB_JDNTRA.WRTDT = DB_ORADT
		'    End If
	End Sub
	
	Sub SCR_FromNHSMTA(ByVal De As Short) 'Generated.
		'    Call DP_SSSMAIN_NHSCD(De, DB_NHSMTA.NHSCD)
		'    Call DP_SSSMAIN_NHSMSTKB(De, DB_NHSMTA.NHSMSTKB)
		'    Call DP_SSSMAIN_NHSNMMKB(De, DB_NHSMTA.NHSNMMKB)
		'    Call DP_SSSMAIN_NHSRN(De, DB_NHSMTA.NHSRN)
	End Sub
	
	Sub NHSMTA_FromSCR(ByVal De As Short) 'Generated.
		'    DB_NHSMTA.NHSCD = RD_SSSMAIN_NHSCD(De)
		'    DB_NHSMTA.NHSMSTKB = RD_SSSMAIN_NHSMSTKB(De)
		'    DB_NHSMTA.NHSNMMKB = RD_SSSMAIN_NHSNMMKB(De)
		'    DB_NHSMTA.NHSRN = RD_SSSMAIN_NHSRN(De)
		'    DB_NHSMTA.OPEID = SSS_OPEID
		'    DB_NHSMTA.CLTID = SSS_CLTID
		'    If Trim$(DB_ORATM) = "" Or Trim$(DB_ORADT) = "" Then
		'        DB_NHSMTA.WRTTM = Format(Now, "hhmmss")
		'        DB_NHSMTA.WRTDT = Format(Now, "YYYYMMDD")
		'    Else
		'        DB_NHSMTA.WRTTM = DB_ORATM
		'        DB_NHSMTA.WRTDT = DB_ORADT
		'    End If
	End Sub
	
	Sub SCR_FromSOUMTA(ByVal De As Short) 'Generated.
		'    Call DP_SSSMAIN_SOUCD(De, DB_SOUMTA.SOUCD)
		'    Call DP_SSSMAIN_SOUNM(De, DB_SOUMTA.SOUNM)
	End Sub
	
	Sub SOUMTA_FromSCR(ByVal De As Short) 'Generated.
		'    DB_SOUMTA.SOUCD = RD_SSSMAIN_SOUCD(De)
		'    DB_SOUMTA.SOUNM = RD_SSSMAIN_SOUNM(De)
		'    DB_SOUMTA.OPEID = SSS_OPEID
		'    DB_SOUMTA.CLTID = SSS_CLTID
		'    If Trim$(DB_ORATM) = "" Or Trim$(DB_ORADT) = "" Then
		'        DB_SOUMTA.WRTTM = Format(Now, "hhmmss")
		'        DB_SOUMTA.WRTDT = Format(Now, "YYYYMMDD")
		'    Else
		'        DB_SOUMTA.WRTTM = DB_ORATM
		'        DB_SOUMTA.WRTDT = DB_ORADT
		'    End If
	End Sub
	
	Sub SCR_FromTANMTA(ByVal De As Short) 'Generated.
		'    Call DP_SSSMAIN_TANCD(De, DB_TANMTA.TANCD)
		'    Call DP_SSSMAIN_TANNM(De, DB_TANMTA.TANNM)
	End Sub
	
	Sub TANMTA_FromSCR(ByVal De As Short) 'Generated.
		'    DB_TANMTA.TANCD = RD_SSSMAIN_TANCD(De)
		'    DB_TANMTA.TANNM = RD_SSSMAIN_TANNM(De)
		'    DB_TANMTA.OPEID = SSS_OPEID
		'    DB_TANMTA.CLTID = SSS_CLTID
		'    If Trim$(DB_ORATM) = "" Or Trim$(DB_ORADT) = "" Then
		'        DB_TANMTA.WRTTM = Format(Now, "hhmmss")
		'        DB_TANMTA.WRTDT = Format(Now, "YYYYMMDD")
		'    Else
		'        DB_TANMTA.WRTTM = DB_ORATM
		'        DB_TANMTA.WRTDT = DB_ORADT
		'    End If
	End Sub
	
	Sub SCR_FromTOKMTA(ByVal De As Short) 'Generated.
		'    Call DP_SSSMAIN_LSTID(De, DB_TOKMTA.LSTID)
		'    Call DP_SSSMAIN_RELFL(De, DB_TOKMTA.RELFL)
		'    Call DP_SSSMAIN_TANCD(De, DB_TOKMTA.TANCD)
		'    Call DP_SSSMAIN_TANNM(De, DB_TOKMTA.TANNM)
		'    Call DP_SSSMAIN_TOKCD(De, DB_TOKMTA.TOKCD)
		'    Call DP_SSSMAIN_TOKJUNKB(De, DB_TOKMTA.TOKJUNKB)
		'    Call DP_SSSMAIN_TOKKDWKB(De, DB_TOKMTA.TOKKDWKB)
		'    Call DP_SSSMAIN_TOKKESCC(De, DB_TOKMTA.TOKKESCC)
		'    Call DP_SSSMAIN_TOKKESDD(De, DB_TOKMTA.TOKKESDD)
		'    Call DP_SSSMAIN_TOKMSTKB(De, DB_TOKMTA.TOKMSTKB)
		'    Call DP_SSSMAIN_TOKNMMKB(De, DB_TOKMTA.TOKNMMKB)
		'    Call DP_SSSMAIN_TOKRN(De, DB_TOKMTA.TOKRN)
		'    Call DP_SSSMAIN_TOKRPSKB(De, DB_TOKMTA.TOKRPSKB)
		'    Call DP_SSSMAIN_TOKSDWKB(De, DB_TOKMTA.TOKSDWKB)
		'    Call DP_SSSMAIN_TOKSEICD(De, DB_TOKMTA.TOKSEICD)
		'    Call DP_SSSMAIN_TOKSMECC(De, DB_TOKMTA.TOKSMECC)
		'    Call DP_SSSMAIN_TOKSMEDD(De, DB_TOKMTA.TOKSMEDD)
		'    Call DP_SSSMAIN_TOKSMEKB(De, DB_TOKMTA.TOKSMEKB)
		'    Call DP_SSSMAIN_TOKZCLKB(De, DB_TOKMTA.TOKZCLKB)
		'    Call DP_SSSMAIN_TOKZEIKB(De, DB_TOKMTA.TOKZEIKB)
		'    Call DP_SSSMAIN_TOKZRNKB(De, DB_TOKMTA.TOKZRNKB)
	End Sub
	
	Sub TOKMTA_FromSCR(ByVal De As Short) 'Generated.
		'    DB_TOKMTA.LSTID = RD_SSSMAIN_LSTID(De)
		'    DB_TOKMTA.RELFL = RD_SSSMAIN_RELFL(De)
		'    DB_TOKMTA.TANCD = RD_SSSMAIN_TANCD(De)
		'    DB_TOKMTA.TANNM = RD_SSSMAIN_TANNM(De)
		'    DB_TOKMTA.TOKCD = RD_SSSMAIN_TOKCD(De)
		'    DB_TOKMTA.TOKJUNKB = RD_SSSMAIN_TOKJUNKB(De)
		'    DB_TOKMTA.TOKKDWKB = RD_SSSMAIN_TOKKDWKB(De)
		'    DB_TOKMTA.TOKKESCC = RD_SSSMAIN_TOKKESCC(De)
		'    DB_TOKMTA.TOKKESDD = RD_SSSMAIN_TOKKESDD(De)
		'    DB_TOKMTA.TOKMSTKB = RD_SSSMAIN_TOKMSTKB(De)
		'    DB_TOKMTA.TOKNMMKB = RD_SSSMAIN_TOKNMMKB(De)
		'    DB_TOKMTA.TOKRN = RD_SSSMAIN_TOKRN(De)
		'    DB_TOKMTA.TOKRPSKB = RD_SSSMAIN_TOKRPSKB(De)
		'    DB_TOKMTA.TOKSDWKB = RD_SSSMAIN_TOKSDWKB(De)
		'    DB_TOKMTA.TOKSEICD = RD_SSSMAIN_TOKSEICD(De)
		'    DB_TOKMTA.TOKSMECC = RD_SSSMAIN_TOKSMECC(De)
		'    DB_TOKMTA.TOKSMEDD = RD_SSSMAIN_TOKSMEDD(De)
		'    DB_TOKMTA.TOKSMEKB = RD_SSSMAIN_TOKSMEKB(De)
		'    DB_TOKMTA.TOKZCLKB = RD_SSSMAIN_TOKZCLKB(De)
		'    DB_TOKMTA.TOKZEIKB = RD_SSSMAIN_TOKZEIKB(De)
		'    DB_TOKMTA.TOKZRNKB = RD_SSSMAIN_TOKZRNKB(De)
		'    DB_TOKMTA.OPEID = SSS_OPEID
		'    DB_TOKMTA.CLTID = SSS_CLTID
		'    If Trim$(DB_ORATM) = "" Or Trim$(DB_ORADT) = "" Then
		'        DB_TOKMTA.WRTTM = Format(Now, "hhmmss")
		'        DB_TOKMTA.WRTDT = Format(Now, "YYYYMMDD")
		'    Else
		'        DB_TOKMTA.WRTTM = DB_ORATM
		'        DB_TOKMTA.WRTDT = DB_ORADT
		'    End If
	End Sub
	
	Sub SCR_FromUODET01(ByVal De As Short) 'Generated.
		'    Call DP_SSSMAIN_CASSU(De, DB_UODET01.CASSU)
		'    Call DP_SSSMAIN_DENCM(De, DB_UODET01.DENCM)
		'    Call DP_SSSMAIN_HINCD(De, DB_UODET01.HINCD)
		'    Call DP_SSSMAIN_HINNMA(De, DB_UODET01.HINNMA)
		'    Call DP_SSSMAIN_HINNMB(De, DB_UODET01.HINNMB)
		'    Call DP_SSSMAIN_IRISU(De, DB_UODET01.IRISU)
		'    Call DP_SSSMAIN_JDNDT(De, DB_UODET01.JDNDT)
		'    Call DP_SSSMAIN_JDNNO(De, DB_UODET01.JDNNO)
		'    Call DP_SSSMAIN_LINCMA(De, DB_UODET01.LINCMA)
		'    Call DP_SSSMAIN_LINCMB(De, DB_UODET01.LINCMB)
		'    Call DP_SSSMAIN_LINNO(De, DB_UODET01.LINNO)
		'    Call DP_SSSMAIN_NHSCD(De, DB_UODET01.NHSCD)
		'    Call DP_SSSMAIN_NHSRN(De, DB_UODET01.NHSRN)
		'    Call DP_SSSMAIN_SBAUODKN(De, DB_UODET01.SBAUODKN)
		'    Call DP_SSSMAIN_TANNM(De, DB_UODET01.TANNM)
		'    Call DP_SSSMAIN_TOKCD(De, DB_UODET01.TOKCD)
		'    Call DP_SSSMAIN_TOKRN(De, DB_UODET01.TOKRN)
		'    Call DP_SSSMAIN_UNTNM(De, DB_UODET01.UNTNM)
		'    Call DP_SSSMAIN_UODKN(De, DB_UODET01.UODKN)
		'    Call DP_SSSMAIN_UODSU(De, DB_UODET01.UODSU)
		'    Call DP_SSSMAIN_UODTK(De, DB_UODET01.UODTK)
	End Sub
	
	Sub UODET01_FromSCR(ByVal De As Short) 'Generated.
		'    DB_UODET01.CASSU = RD_SSSMAIN_CASSU(De)
		'    DB_UODET01.DENCM = RD_SSSMAIN_DENCM(De)
		'    DB_UODET01.HINCD = RD_SSSMAIN_HINCD(De)
		'    DB_UODET01.HINNMA = RD_SSSMAIN_HINNMA(De)
		'    DB_UODET01.HINNMB = RD_SSSMAIN_HINNMB(De)
		'    DB_UODET01.IRISU = RD_SSSMAIN_IRISU(De)
		'    DB_UODET01.JDNDT = RD_SSSMAIN_JDNDT(De)
		'    DB_UODET01.JDNNO = RD_SSSMAIN_JDNNO(De)
		'    DB_UODET01.LINCMA = RD_SSSMAIN_LINCMA(De)
		'    DB_UODET01.LINCMB = RD_SSSMAIN_LINCMB(De)
		'    DB_UODET01.LINNO = RD_SSSMAIN_LINNO(De)
		'    DB_UODET01.NHSCD = RD_SSSMAIN_NHSCD(De)
		'    DB_UODET01.NHSRN = RD_SSSMAIN_NHSRN(De)
		'    DB_UODET01.SBAUODKN = RD_SSSMAIN_SBAUODKN(De)
		'    DB_UODET01.TANNM = RD_SSSMAIN_TANNM(De)
		'    DB_UODET01.TOKCD = RD_SSSMAIN_TOKCD(De)
		'    DB_UODET01.TOKRN = RD_SSSMAIN_TOKRN(De)
		'    DB_UODET01.UNTNM = RD_SSSMAIN_UNTNM(De)
		'    DB_UODET01.UODKN = RD_SSSMAIN_UODKN(De)
		'    DB_UODET01.UODSU = RD_SSSMAIN_UODSU(De)
		'    DB_UODET01.UODTK = RD_SSSMAIN_UODTK(De)
		'    If Trim$(DB_ORATM) = "" Or Trim$(DB_ORADT) = "" Then
		'        DB_UODET01.WRTTM = Format(Now, "hhmmss")
		'        DB_UODET01.WRTDT = Format(Now, "YYYYMMDD")
		'    Else
		'        DB_UODET01.WRTTM = DB_ORATM
		'        DB_UODET01.WRTDT = DB_ORADT
		'    End If
	End Sub
	
	Sub HINMTB_FromJDNTRA() 'Generated.
		'    Dim I As Integer
		'
		'    DB_HINMTB.HINCD = DB_JDNTRA.HINCD
		'    DB_HINMTB.HINMSTKB = DB_JDNTRA.HINMSTKB
		'    DB_HINMTB.RELJDNSU = DB_HINMTB.RELJDNSU + DB_JDNTRA.UODSU * SSS_SMFKB
		'    DB_HINMTB.SOUCD = DB_JDNTRA.SOUCD
		'    DB_HINMTB.OPEID = SSS_OPEID
		'    DB_HINMTB.CLTID = SSS_CLTID
		'    If Trim$(DB_ORATM) = "" Or Trim$(DB_ORADT) = "" Then
		'        DB_HINMTB.WRTTM = Format(Now, "hhmmss")
		'        DB_HINMTB.WRTDT = Format(Now, "YYYYMMDD")
		'    Else
		'        DB_HINMTB.WRTTM = DB_ORATM
		'        DB_HINMTB.WRTDT = DB_ORADT
		'    End If
	End Sub
	
	Sub UODET01_FromTOKMTA() 'Generated.
		'    Dim I As Integer
		'
		'    DB_UODET01.TOKADA = DB_TOKMTA.TOKADA
		'    DB_UODET01.TOKADB = DB_TOKMTA.TOKADB
		'    DB_UODET01.TOKADC = DB_TOKMTA.TOKADC
		'    DB_UODET01.TOKCD = DB_TOKMTA.TOKCD
		'    DB_UODET01.TOKNMA = DB_TOKMTA.TOKNMA
		'    DB_UODET01.TOKNMB = DB_TOKMTA.TOKNMB
		'    DB_UODET01.TOKZP = DB_TOKMTA.TOKZP
		'    If Trim$(DB_ORATM) = "" Or Trim$(DB_ORADT) = "" Then
		'    Else
		'    End If
	End Sub
	
	Sub UpdSmf() 'Generated.
	End Sub
	
	Sub SetBuf(ByVal Fno As Short) 'Generated.
		'    Select Case Fno
		'        Case DBN_JDNTRA: LSet G_LB = DB_JDNTRA
		'        Case DBN_JDNTHA: LSet G_LB = DB_JDNTHA
		'        Case DBN_TOKMTA: LSet G_LB = DB_TOKMTA
		'        Case DBN_TANMTA: LSet G_LB = DB_TANMTA
		'        Case DBN_NHSMTA: LSet G_LB = DB_NHSMTA
		'        Case DBN_SOUMTA: LSet G_LB = DB_SOUMTA
		'        Case DBN_HINMTA: LSet G_LB = DB_HINMTA
		'        Case DBN_SYSTBA: LSet G_LB = DB_SYSTBA
		'        Case DBN_SYSTBB: LSet G_LB = DB_SYSTBB
		'        Case DBN_SYSTBC: LSet G_LB = DB_SYSTBC
		'        Case DBN_SYSTBD: LSet G_LB = DB_SYSTBD
		'        Case DBN_SYSTBF: LSet G_LB = DB_SYSTBF
		'        Case DBN_SYSTBG: LSet G_LB = DB_SYSTBG
		'        Case DBN_SYSTBH: LSet G_LB = DB_SYSTBH
		'        Case DBN_CLSMTA: LSet G_LB = DB_CLSMTA
		'        Case DBN_CLSMTB: LSet G_LB = DB_CLSMTB
		'        Case DBN_HINMTB: LSet G_LB = DB_HINMTB
		'        Case DBN_TOKMTB: LSet G_LB = DB_TOKMTB
		'        Case DBN_SYSTBI: LSet G_LB = DB_SYSTBI
		'    End Select
	End Sub
	
	Sub ResetBuf(ByVal Fno As Short) 'Generated.
		'    Select Case Fno
		'        Case DBN_JDNTRA: LSet DB_JDNTRA = G_LB
		'        Case DBN_JDNTHA: LSet DB_JDNTHA = G_LB
		'        Case DBN_TOKMTA: LSet DB_TOKMTA = G_LB
		'        Case DBN_TANMTA: LSet DB_TANMTA = G_LB
		'        Case DBN_NHSMTA: LSet DB_NHSMTA = G_LB
		'        Case DBN_SOUMTA: LSet DB_SOUMTA = G_LB
		'        Case DBN_HINMTA: LSet DB_HINMTA = G_LB
		'        Case DBN_SYSTBA: LSet DB_SYSTBA = G_LB
		'        Case DBN_SYSTBB: LSet DB_SYSTBB = G_LB
		'        Case DBN_SYSTBC: LSet DB_SYSTBC = G_LB
		'        Case DBN_SYSTBD: LSet DB_SYSTBD = G_LB
		'        Case DBN_SYSTBF: LSet DB_SYSTBF = G_LB
		'        Case DBN_SYSTBG: LSet DB_SYSTBG = G_LB
		'        Case DBN_SYSTBH: LSet DB_SYSTBH = G_LB
		'        Case DBN_CLSMTA: LSet DB_CLSMTA = G_LB
		'        Case DBN_CLSMTB: LSet DB_CLSMTB = G_LB
		'        Case DBN_HINMTB: LSet DB_HINMTB = G_LB
		'        Case DBN_TOKMTB: LSet DB_TOKMTB = G_LB
		'        Case DBN_SYSTBI: LSet DB_SYSTBI = G_LB
		'    End Select
	End Sub
	
	Function RecordFromObject(ByVal Fno As Short) As Short 'Generated.
		'Dim Rtc As Integer
		'    Select Case Fno
		'        Case DBN_UODET01: Rtc = UODET01_FromObject()
		'        Case Else:
		'    End Select
		'    RecordFromObject = Rtc
	End Function
	
	Function ObjectFromRecord(ByVal Fno As Short) As Short 'Generated.
		'Dim Rtc As Integer
		'    Select Case Fno
		'        Case DBN_UODET01: Rtc = UODET01_FromRecord()
		'        Case Else:
		'    End Select
		'    ObjectFromRecord = Rtc
	End Function
End Module